# Generated by Django 5.0.7 on 2024-08-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasecontract',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма депозита (необязательное поле)', max_digits=10, null=True, verbose_name='Сумма депозита'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='end_date',
            field=models.DateTimeField(help_text='Дата и время окончания аренды', verbose_name='Дата окончания аренды'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='property',
            field=models.ForeignKey(help_text='Арендуемая недвижимость', on_delete=django.db.models.deletion.CASCADE, to='realestate.property', verbose_name='Ссылка на арендуемую недвижимость'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма аренды', max_digits=10, verbose_name='Сумма аренды'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='rent_period',
            field=models.CharField(choices=[('Hour', 'Час'), ('Day', 'Сутки'), ('Month', 'Месяц')], help_text='Период аренды (часы, сутки, месяцы)', max_length=20, verbose_name='Период аренды'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='start_date',
            field=models.DateTimeField(help_text='Дата и время начала аренды', verbose_name='Дата начала аренды'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='tenant',
            field=models.ForeignKey(help_text='Арендатор', on_delete=django.db.models.deletion.CASCADE, to='realestate.tenant', verbose_name='Ссылка на арендатора'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.leasecontract', verbose_name='Ссылка на договор аренды'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время совершения платежа'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='minimum_rental_unit',
            field=models.CharField(choices=[('Hour', 'в час'), ('Day', 'в сутки'), ('Month', 'в месяц')], help_text='Единица измерения минимального периода сдачи (часы, дни, месяцы)', max_length=5, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='property',
            name='minimum_rental_value',
            field=models.IntegerField(help_text='Минимальный период сдачи', verbose_name='Минимальный период сдачи'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.owner', verbose_name='Владелец недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость аренды', max_digits=10, verbose_name='Стоимость аренды'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_period',
            field=models.CharField(choices=[('Hour', 'в час'), ('Day', 'в сутки'), ('Month', 'в месяц')], help_text='Стоимость за период: в час, в сутки или в месяц', max_length=20, verbose_name='Стоимость за период'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Квартира'), ('House', 'Дом'), ('Commercial', 'Коммерческая недвижимость'), ('Land', 'Земельный участок')], max_length=20, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(choices=[('Hourly', 'Почасовая аренда'), ('Daily', 'Посуточная аренда'), ('LongTerm', 'Длительная аренда')], help_text='Тип ренты (почасовая, посуточная, длительная аренда)', max_length=20, verbose_name='Тип ренты'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес арендатора'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта арендатора'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя арендатора'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия арендатора'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона арендатора'),
        ),
    ]
