# Generated by Django 5.0.7 on 2024-08-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realestate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец недвижимости'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='property',
            field=models.ForeignKey(help_text='Арендуемая недвижимость', on_delete=django.db.models.deletion.CASCADE, to='realestate.property', verbose_name='Ссылка на арендуемую недвижимость'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='tenant',
            field=models.ForeignKey(help_text='Арендатор', on_delete=django.db.models.deletion.CASCADE, to='realestate.tenant', verbose_name='Ссылка на арендатора'),
        ),
    ]
