# Generated by Django 5.0.7 on 2024-08-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, help_text='Дата следующего платежа', null=True, verbose_name='Дата следующего платежа'),
        ),
    ]
