# Generated by Django 5.0.7 on 2024-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_leasecontract_next_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasecontract',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Дата следующего платежа', null=True, verbose_name='Дата следующего платежа'),
        ),
    ]
