PROPERTY_TYPE_APARTMENT = 'Apartment'
PROPERTY_TYPE_HOUSE = 'House'
PROPERTY_TYPE_COMMERCIAL = 'Commercial'
PROPERTY_TYPE_LAND = 'Land'

PERIOD_HOUR = 'Hour'
PERIOD_DAY = 'Day'
PERIOD_MONTH = 'Month'

RENTAL_TYPE_HOURLY = 'Hourly'
RENTAL_TYPE_DAILY = 'Daily'
RENTAL_TYPE_LONG_TERM = 'LongTerm'